package org.openfact.representations.idm.ubl;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import org.openfact.representations.idm.ubl.common.BillingReferenceModel;
import org.openfact.representations.idm.ubl.common.CustomerPartyModel;
import org.openfact.representations.idm.ubl.common.DebitNoteLineModel;
import org.openfact.representations.idm.ubl.common.DocumentReferenceModel;
import org.openfact.representations.idm.ubl.common.ExchangeRateModel;
import org.openfact.representations.idm.ubl.common.MonetaryTotalModel;
import org.openfact.representations.idm.ubl.common.OrderReferenceModel;
import org.openfact.representations.idm.ubl.common.PartyModel;
import org.openfact.representations.idm.ubl.common.PaymentModel;
import org.openfact.representations.idm.ubl.common.PeriodModel;
import org.openfact.representations.idm.ubl.common.ResponseModel;
import org.openfact.representations.idm.ubl.common.SignatureModel;
import org.openfact.representations.idm.ubl.common.SupplierPartyModel;
import org.openfact.representations.idm.ubl.common.TaxTotalModel;
import org.openfact.representations.idm.ubl.common.UBLExtensionsModel;

public class DebitNoteModel {
    protected UBLExtensionsModel UBLExtensions;
    protected String UBLVersionID;
    protected String CustomizationID;
    protected String ProfileID;
    protected String ID;
    protected boolean CopyIndicator;
    protected String UUID;
    protected LocalDate IssueDate;
    protected LocalTime IssueTime;
    protected List<String> Note;
    protected LocalDate TaxPointDate;
    protected String DocumentCurrencyCode;
    protected String TaxCurrencyCode;
    protected String PricingCurrencyCode;
    protected String PaymentCurrencyCode;
    protected String PaymentAlternativeCurrencyCode;
    protected String AccountingCostCode;
    protected String AccountingCost;
    protected BigDecimal LineCountNumeric;
    protected List<PeriodModel> InvoicePeriod;
    protected List<ResponseModel> DiscrepancyResponse;
    protected OrderReferenceModel OrderReference;
    protected List<BillingReferenceModel> BillingReference;
    protected List<DocumentReferenceModel> DespatchDocumentReference;
    protected List<DocumentReferenceModel> ReceiptDocumentReference;
    protected List<DocumentReferenceModel> ContractDocumentReference;
    protected List<DocumentReferenceModel> AdditionalDocumentReference;
    protected List<SignatureModel> Signature;
    protected SupplierPartyModel AccountingSupplierParty;
    protected CustomerPartyModel AccountingCustomerParty;
    protected PartyModel PayeeParty;
    protected PartyModel TaxRepresentativeParty;
    protected List<PaymentModel> PrepaidPayment;
    protected ExchangeRateModel TaxExchangeRate;
    protected ExchangeRateModel PricingExchangeRate;
    protected ExchangeRateModel PaymentExchangeRate;
    protected ExchangeRateModel PaymentAlternativeExchangeRate;
    protected List<TaxTotalModel> TaxTotal;
    protected MonetaryTotalModel RequestedMonetaryTotal;
    protected List<DebitNoteLineModel> DebitNoteLine;
    protected String Id;
}