package org.openfact.representations.idm.ubl;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import org.openfact.representations.idm.ubl.common.AllowanceChargeRepresentation;
import org.openfact.representations.idm.ubl.common.BillingReferenceRepresentation;
import org.openfact.representations.idm.ubl.common.CustomerPartyRepresentation;
import org.openfact.representations.idm.ubl.common.DeliveryRepresentation;
import org.openfact.representations.idm.ubl.common.DeliveryTermsRepresentation;
import org.openfact.representations.idm.ubl.common.DocumentReferenceRepresentation;
import org.openfact.representations.idm.ubl.common.ExchangeRateRepresentation;
import org.openfact.representations.idm.ubl.common.InvoiceLineRepresentation;
import org.openfact.representations.idm.ubl.common.MonetaryTotalRepresentation;
import org.openfact.representations.idm.ubl.common.OrderReferenceRepresentation;
import org.openfact.representations.idm.ubl.common.PartyRepresentation;
import org.openfact.representations.idm.ubl.common.PaymentMeansRepresentation;
import org.openfact.representations.idm.ubl.common.PaymentRepresentation;
import org.openfact.representations.idm.ubl.common.PaymentTermsRepresentation;
import org.openfact.representations.idm.ubl.common.PeriodRepresentation;
import org.openfact.representations.idm.ubl.common.SignatureRepresentation;
import org.openfact.representations.idm.ubl.common.SupplierPartyRepresentation;
import org.openfact.representations.idm.ubl.common.TaxTotalRepresentation;
import org.openfact.representations.idm.ubl.common.UBLExtensionsRepresentation;

public class InvoiceRepresentation {
    private UBLExtensionsRepresentation UBLExtensions;
    private String UBLVersionID;
    private String CustomizationID;
    private String ProfileID;
    private String ID;
    private boolean CopyIndicator;
    private String UUID;
    private LocalDate IssueDate;
    private LocalTime IssueTime;
    private String InvoiceRepresentationCode;
    private List<String> Note;
    private LocalDate TaxPointDate;
    private String DocumentCurrencyCode;
    private String TaxCurrencyCode;
    private String PricingCurrencyCode;
    private String PaymentCurrencyCode;
    private String PaymentAlternativeCurrencyCode;
    private String AccountingCostCode;
    private String AccountingCost;
    private BigDecimal LineCountNumeric;
    private List<PeriodRepresentation> InvoicePeriod;
    private OrderReferenceRepresentation OrderReference;
    private List<BillingReferenceRepresentation> BillingReference;
    private List<DocumentReferenceRepresentation> DespatchDocumentReference;
    private List<DocumentReferenceRepresentation> ReceiptDocumentReference;
    private List<DocumentReferenceRepresentation> OriginatorDocumentReference;
    private List<DocumentReferenceRepresentation> ContractDocumentReference;
    private List<DocumentReferenceRepresentation> AdditionalDocumentReference;
    private List<SignatureRepresentation> Signature;
    private SupplierPartyRepresentation AccountingSupplierParty;
    private CustomerPartyRepresentation AccountingCustomerParty;
    private PartyRepresentation PayeeParty;
    private CustomerPartyRepresentation BuyerCustomerParty;
    private SupplierPartyRepresentation SellerSupplierParty;
    private PartyRepresentation TaxRepresentativeParty;
    private List<DeliveryRepresentation> Delivery;
    private DeliveryTermsRepresentation DeliveryTerms;
    private List<PaymentMeansRepresentation> PaymentMeans;
    private List<PaymentTermsRepresentation> PaymentTerms;
    private List<PaymentRepresentation> PrepaidPayment;
    private List<AllowanceChargeRepresentation> AllowanceCharge;
    private ExchangeRateRepresentation TaxExchangeRate;
    private ExchangeRateRepresentation PricingExchangeRate;
    private ExchangeRateRepresentation PaymentExchangeRate;
    private ExchangeRateRepresentation PaymentAlternativeExchangeRate;
    private List<TaxTotalRepresentation> TaxTotal;
    private MonetaryTotalRepresentation LegalMonetaryTotal;
    private List<InvoiceLineRepresentation> InvoiceLine;
    private String Id;
}