//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import org.openfact.models.ubl.common.ActionCodeType;
import org.openfact.models.ubl.common.ContentUnitQuantityType;
import org.openfact.models.ubl.common.ContractSubdivisionType;
import org.openfact.models.ubl.common.CustomerPartyType;
import org.openfact.models.ubl.common.DocumentReferenceType;
import org.openfact.models.ubl.common.IDType;
import org.openfact.models.ubl.common.ItemComparisonType;
import org.openfact.models.ubl.common.ItemLocationQuantityType;
import org.openfact.models.ubl.common.ItemType;
import org.openfact.models.ubl.common.LifeCycleStatusCodeType;
import org.openfact.models.ubl.common.MaximumOrderQuantityType;
import org.openfact.models.ubl.common.MinimumOrderQuantityType;
import org.openfact.models.ubl.common.NoteType;
import org.openfact.models.ubl.common.OrderQuantityIncrementNumericType;
import org.openfact.models.ubl.common.OrderableIndicatorType;
import org.openfact.models.ubl.common.OrderableUnitType;
import org.openfact.models.ubl.common.PackLevelCodeType;
import org.openfact.models.ubl.common.PartyType;
import org.openfact.models.ubl.common.PeriodType;
import org.openfact.models.ubl.common.RelatedItemType;
import org.openfact.models.ubl.common.SupplierPartyType;
import org.openfact.models.ubl.common.WarrantyInformationType;

public class CatalogueLineType {

    protected IDType ID;
    protected ActionCodeType actionCode;
    protected LifeCycleStatusCodeType lifeCycleStatusCode;
    protected ContractSubdivisionType contractSubdivision;
    protected List<NoteType> note;
    protected OrderableIndicatorType orderableIndicator;
    protected OrderableUnitType orderableUnit;
    protected ContentUnitQuantityType contentUnitQuantity;
    protected OrderQuantityIncrementNumericType orderQuantityIncrementNumeric;
    protected MinimumOrderQuantityType minimumOrderQuantity;
    protected MaximumOrderQuantityType maximumOrderQuantity;
    protected List<WarrantyInformationType> warrantyInformation;
    protected PackLevelCodeType packLevelCode;
    protected CustomerPartyType contractorCustomerParty;
    protected SupplierPartyType sellerSupplierParty;
    protected PartyType warrantyParty;
    protected PeriodType warrantyValidityPeriod;
    protected PeriodType lineValidityPeriod;
    protected List<ItemComparisonType> itemComparison;
    protected List<RelatedItemType> componentRelatedItem;
    protected List<RelatedItemType> accessoryRelatedItem;
    protected List<RelatedItemType> requiredRelatedItem;
    protected List<RelatedItemType> replacementRelatedItem;
    protected List<RelatedItemType> complementaryRelatedItem;
    protected List<ItemLocationQuantityType> requiredItemLocationQuantity;
    protected List<DocumentReferenceType> documentReference;
    protected ItemType item;
    protected String id;

    public IDType getID() {
        return ID;
    }

    public void setID(IDType value) {
        this.ID = value;
    }

    public ActionCodeType getActionCode() {
        return actionCode;
    }

    public void setActionCode(ActionCodeType value) {
        this.actionCode = value;
    }

    public LifeCycleStatusCodeType getLifeCycleStatusCode() {
        return lifeCycleStatusCode;
    }

    public void setLifeCycleStatusCode(LifeCycleStatusCodeType value) {
        this.lifeCycleStatusCode = value;
    }

    public ContractSubdivisionType getContractSubdivision() {
        return contractSubdivision;
    }

    public void setContractSubdivision(ContractSubdivisionType value) {
        this.contractSubdivision = value;
    }

    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }

    public void setNote(List<NoteType> note) {
        this.note = note;
    }

    public OrderableIndicatorType getOrderableIndicator() {
        return orderableIndicator;
    }

    public void setOrderableIndicator(OrderableIndicatorType value) {
        this.orderableIndicator = value;
    }

    public OrderableUnitType getOrderableUnit() {
        return orderableUnit;
    }

    public void setOrderableUnit(OrderableUnitType value) {
        this.orderableUnit = value;
    }

    public ContentUnitQuantityType getContentUnitQuantity() {
        return contentUnitQuantity;
    }

    public void setContentUnitQuantity(ContentUnitQuantityType value) {
        this.contentUnitQuantity = value;
    }

    public OrderQuantityIncrementNumericType getOrderQuantityIncrementNumeric() {
        return orderQuantityIncrementNumeric;
    }

    public void setOrderQuantityIncrementNumeric(OrderQuantityIncrementNumericType value) {
        this.orderQuantityIncrementNumeric = value;
    }

    public MinimumOrderQuantityType getMinimumOrderQuantity() {
        return minimumOrderQuantity;
    }

    public void setMinimumOrderQuantity(MinimumOrderQuantityType value) {
        this.minimumOrderQuantity = value;
    }

    public MaximumOrderQuantityType getMaximumOrderQuantity() {
        return maximumOrderQuantity;
    }

    public void setMaximumOrderQuantity(MaximumOrderQuantityType value) {
        this.maximumOrderQuantity = value;
    }

    public List<WarrantyInformationType> getWarrantyInformation() {
        if (warrantyInformation == null) {
            warrantyInformation = new ArrayList<WarrantyInformationType>();
        }
        return this.warrantyInformation;
    }

    public void setWarrantyInformation(List<WarrantyInformationType> warrantyInformation) {
        this.warrantyInformation = warrantyInformation;
    }

    public PackLevelCodeType getPackLevelCode() {
        return packLevelCode;
    }

    public void setPackLevelCode(PackLevelCodeType value) {
        this.packLevelCode = value;
    }

    public CustomerPartyType getContractorCustomerParty() {
        return contractorCustomerParty;
    }

    public void setContractorCustomerParty(CustomerPartyType value) {
        this.contractorCustomerParty = value;
    }

    public SupplierPartyType getSellerSupplierParty() {
        return sellerSupplierParty;
    }

    public void setSellerSupplierParty(SupplierPartyType value) {
        this.sellerSupplierParty = value;
    }

    public PartyType getWarrantyParty() {
        return warrantyParty;
    }

    public void setWarrantyParty(PartyType value) {
        this.warrantyParty = value;
    }

    public PeriodType getWarrantyValidityPeriod() {
        return warrantyValidityPeriod;
    }

    public void setWarrantyValidityPeriod(PeriodType value) {
        this.warrantyValidityPeriod = value;
    }

    public PeriodType getLineValidityPeriod() {
        return lineValidityPeriod;
    }

    public void setLineValidityPeriod(PeriodType value) {
        this.lineValidityPeriod = value;
    }

    public List<ItemComparisonType> getItemComparison() {
        if (itemComparison == null) {
            itemComparison = new ArrayList<ItemComparisonType>();
        }
        return this.itemComparison;
    }

    public void setItemComparison(List<ItemComparisonType> itemComparison) {
        this.itemComparison = itemComparison;
    }

    public List<RelatedItemType> getComponentRelatedItem() {
        if (componentRelatedItem == null) {
            componentRelatedItem = new ArrayList<RelatedItemType>();
        }
        return this.componentRelatedItem;
    }

    public void setComponentRelatedItem(List<RelatedItemType> componentRelatedItem) {
        this.componentRelatedItem = componentRelatedItem;
    }

    public List<RelatedItemType> getAccessoryRelatedItem() {
        if (accessoryRelatedItem == null) {
            accessoryRelatedItem = new ArrayList<RelatedItemType>();
        }
        return this.accessoryRelatedItem;
    }

    public void setAccessoryRelatedItem(List<RelatedItemType> accessoryRelatedItem) {
        this.accessoryRelatedItem = accessoryRelatedItem;
    }

    public List<RelatedItemType> getRequiredRelatedItem() {
        if (requiredRelatedItem == null) {
            requiredRelatedItem = new ArrayList<RelatedItemType>();
        }
        return this.requiredRelatedItem;
    }

    public void setRequiredRelatedItem(List<RelatedItemType> requiredRelatedItem) {
        this.requiredRelatedItem = requiredRelatedItem;
    }

    public List<RelatedItemType> getReplacementRelatedItem() {
        if (replacementRelatedItem == null) {
            replacementRelatedItem = new ArrayList<RelatedItemType>();
        }
        return this.replacementRelatedItem;
    }

    public void setReplacementRelatedItem(List<RelatedItemType> replacementRelatedItem) {
        this.replacementRelatedItem = replacementRelatedItem;
    }

    public List<RelatedItemType> getComplementaryRelatedItem() {
        if (complementaryRelatedItem == null) {
            complementaryRelatedItem = new ArrayList<RelatedItemType>();
        }
        return this.complementaryRelatedItem;
    }

    public void setComplementaryRelatedItem(List<RelatedItemType> complementaryRelatedItem) {
        this.complementaryRelatedItem = complementaryRelatedItem;
    }

    public List<ItemLocationQuantityType> getRequiredItemLocationQuantity() {
        if (requiredItemLocationQuantity == null) {
            requiredItemLocationQuantity = new ArrayList<ItemLocationQuantityType>();
        }
        return this.requiredItemLocationQuantity;
    }

    public void setRequiredItemLocationQuantity(List<ItemLocationQuantityType> requiredItemLocationQuantity) {
        this.requiredItemLocationQuantity = requiredItemLocationQuantity;
    }

    public List<DocumentReferenceType> getDocumentReference() {
        if (documentReference == null) {
            documentReference = new ArrayList<DocumentReferenceType>();
        }
        return this.documentReference;
    }

    public void setDocumentReference(List<DocumentReferenceType> documentReference) {
        this.documentReference = documentReference;
    }

    public ItemType getItem() {
        return item;
    }

    public void setItem(ItemType value) {
        this.item = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
