//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.ubl.common;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import org.openfact.models.ubl.common.ActualDespatchDateType;
import org.openfact.models.ubl.common.ActualDespatchTimeType;
import org.openfact.models.ubl.common.AddressType;
import org.openfact.models.ubl.common.ContactType;
import org.openfact.models.ubl.common.EstimatedDespatchDateType;
import org.openfact.models.ubl.common.EstimatedDespatchTimeType;
import org.openfact.models.ubl.common.IDType;
import org.openfact.models.ubl.common.PartyType;
import org.openfact.models.ubl.common.RequestedDespatchDateType;
import org.openfact.models.ubl.common.RequestedDespatchTimeType;

public class DespatchType {

    protected IDType ID;
    protected RequestedDespatchDateType requestedDespatchDate;
    protected RequestedDespatchTimeType requestedDespatchTime;
    protected EstimatedDespatchDateType estimatedDespatchDate;
    protected EstimatedDespatchTimeType estimatedDespatchTime;
    protected ActualDespatchDateType actualDespatchDate;
    protected ActualDespatchTimeType actualDespatchTime;
    protected AddressType despatchAddress;
    protected PartyType despatchParty;
    protected ContactType contact;
    protected String id;

    public IDType getID() {
        return ID;
    }

    public void setID(IDType value) {
        this.ID = value;
    }

    public RequestedDespatchDateType getRequestedDespatchDate() {
        return requestedDespatchDate;
    }

    public void setRequestedDespatchDate(RequestedDespatchDateType value) {
        this.requestedDespatchDate = value;
    }

    public RequestedDespatchTimeType getRequestedDespatchTime() {
        return requestedDespatchTime;
    }

    public void setRequestedDespatchTime(RequestedDespatchTimeType value) {
        this.requestedDespatchTime = value;
    }

    public EstimatedDespatchDateType getEstimatedDespatchDate() {
        return estimatedDespatchDate;
    }

    public void setEstimatedDespatchDate(EstimatedDespatchDateType value) {
        this.estimatedDespatchDate = value;
    }

    public EstimatedDespatchTimeType getEstimatedDespatchTime() {
        return estimatedDespatchTime;
    }

    public void setEstimatedDespatchTime(EstimatedDespatchTimeType value) {
        this.estimatedDespatchTime = value;
    }

    public ActualDespatchDateType getActualDespatchDate() {
        return actualDespatchDate;
    }

    public void setActualDespatchDate(ActualDespatchDateType value) {
        this.actualDespatchDate = value;
    }

    public ActualDespatchTimeType getActualDespatchTime() {
        return actualDespatchTime;
    }

    public void setActualDespatchTime(ActualDespatchTimeType value) {
        this.actualDespatchTime = value;
    }

    public AddressType getDespatchAddress() {
        return despatchAddress;
    }

    public void setDespatchAddress(AddressType value) {
        this.despatchAddress = value;
    }

    public PartyType getDespatchParty() {
        return despatchParty;
    }

    public void setDespatchParty(PartyType value) {
        this.despatchParty = value;
    }

    public ContactType getContact() {
        return contact;
    }

    public void setContact(ContactType value) {
        this.contact = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
