//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import org.openfact.models.ubl.common.AddressType;
import org.openfact.models.ubl.common.DeliveryUnitType;
import org.openfact.models.ubl.common.HazardousRiskIndicatorType;
import org.openfact.models.ubl.common.LeadTimeMeasureType;
import org.openfact.models.ubl.common.MaximumQuantityType;
import org.openfact.models.ubl.common.MinimumQuantityType;
import org.openfact.models.ubl.common.PriceType;
import org.openfact.models.ubl.common.TaxCategoryType;
import org.openfact.models.ubl.common.TradingRestrictionsType;

public class ItemLocationQuantityType {

    protected LeadTimeMeasureType leadTimeMeasure;
    protected MinimumQuantityType minimumQuantity;
    protected MaximumQuantityType maximumQuantity;
    protected HazardousRiskIndicatorType hazardousRiskIndicator;
    protected List<TradingRestrictionsType> tradingRestrictions;
    protected List<AddressType> applicableTerritoryAddress;
    protected PriceType price;
    protected List<DeliveryUnitType> deliveryUnit;
    protected List<TaxCategoryType> applicableTaxCategory;
    protected String id;

    public LeadTimeMeasureType getLeadTimeMeasure() {
        return leadTimeMeasure;
    }

    public void setLeadTimeMeasure(LeadTimeMeasureType value) {
        this.leadTimeMeasure = value;
    }

    public MinimumQuantityType getMinimumQuantity() {
        return minimumQuantity;
    }

    public void setMinimumQuantity(MinimumQuantityType value) {
        this.minimumQuantity = value;
    }

    public MaximumQuantityType getMaximumQuantity() {
        return maximumQuantity;
    }

    public void setMaximumQuantity(MaximumQuantityType value) {
        this.maximumQuantity = value;
    }

    public HazardousRiskIndicatorType getHazardousRiskIndicator() {
        return hazardousRiskIndicator;
    }

    public void setHazardousRiskIndicator(HazardousRiskIndicatorType value) {
        this.hazardousRiskIndicator = value;
    }

    public List<TradingRestrictionsType> getTradingRestrictions() {
        if (tradingRestrictions == null) {
            tradingRestrictions = new ArrayList<TradingRestrictionsType>();
        }
        return this.tradingRestrictions;
    }

    public void setTradingRestrictions(List<TradingRestrictionsType> tradingRestrictions) {
        this.tradingRestrictions = tradingRestrictions;
    }

    public List<AddressType> getApplicableTerritoryAddress() {
        if (applicableTerritoryAddress == null) {
            applicableTerritoryAddress = new ArrayList<AddressType>();
        }
        return this.applicableTerritoryAddress;
    }

    public void setApplicableTerritoryAddress(List<AddressType> applicableTerritoryAddress) {
        this.applicableTerritoryAddress = applicableTerritoryAddress;
    }

    public PriceType getPrice() {
        return price;
    }

    public void setPrice(PriceType value) {
        this.price = value;
    }

    public List<DeliveryUnitType> getDeliveryUnit() {
        if (deliveryUnit == null) {
            deliveryUnit = new ArrayList<DeliveryUnitType>();
        }
        return this.deliveryUnit;
    }

    public void setDeliveryUnit(List<DeliveryUnitType> deliveryUnit) {
        this.deliveryUnit = deliveryUnit;
    }

    public List<TaxCategoryType> getApplicableTaxCategory() {
        if (applicableTaxCategory == null) {
            applicableTaxCategory = new ArrayList<TaxCategoryType>();
        }
        return this.applicableTaxCategory;
    }

    public void setApplicableTaxCategory(List<TaxCategoryType> applicableTaxCategory) {
        this.applicableTaxCategory = applicableTaxCategory;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
