//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import org.openfact.models.ubl.common.ItemPropertyType;
import org.openfact.models.ubl.common.LotIdentificationType;
import org.openfact.models.ubl.common.ManufactureDateType;
import org.openfact.models.ubl.common.ManufactureTimeType;
import org.openfact.models.ubl.common.ProductTraceIDType;
import org.openfact.models.ubl.common.RegistrationIDType;
import org.openfact.models.ubl.common.SerialIDType;

public class ItemInstanceType {

    protected ProductTraceIDType productTraceID;
    protected ManufactureDateType manufactureDate;
    protected ManufactureTimeType manufactureTime;
    protected RegistrationIDType registrationID;
    protected SerialIDType serialID;
    protected List<ItemPropertyType> additionalItemProperty;
    protected LotIdentificationType lotIdentification;
    protected String id;

    public ProductTraceIDType getProductTraceID() {
        return productTraceID;
    }

    public void setProductTraceID(ProductTraceIDType value) {
        this.productTraceID = value;
    }

    public ManufactureDateType getManufactureDate() {
        return manufactureDate;
    }

    public void setManufactureDate(ManufactureDateType value) {
        this.manufactureDate = value;
    }

    public ManufactureTimeType getManufactureTime() {
        return manufactureTime;
    }

    public void setManufactureTime(ManufactureTimeType value) {
        this.manufactureTime = value;
    }

    public RegistrationIDType getRegistrationID() {
        return registrationID;
    }

    public void setRegistrationID(RegistrationIDType value) {
        this.registrationID = value;
    }

    public SerialIDType getSerialID() {
        return serialID;
    }

    public void setSerialID(SerialIDType value) {
        this.serialID = value;
    }

    public List<ItemPropertyType> getAdditionalItemProperty() {
        if (additionalItemProperty == null) {
            additionalItemProperty = new ArrayList<ItemPropertyType>();
        }
        return this.additionalItemProperty;
    }

    public void setAdditionalItemProperty(List<ItemPropertyType> additionalItemProperty) {
        this.additionalItemProperty = additionalItemProperty;
    }

    public LotIdentificationType getLotIdentification() {
        return lotIdentification;
    }

    public void setLotIdentification(LotIdentificationType value) {
        this.lotIdentification = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
