//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.ubl.common;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import org.openfact.models.ubl.common.AllowanceTotalAmountType;
import org.openfact.models.ubl.common.ChargeTotalAmountType;
import org.openfact.models.ubl.common.LineExtensionAmountType;
import org.openfact.models.ubl.common.PayableAmountType;
import org.openfact.models.ubl.common.PayableRoundingAmountType;
import org.openfact.models.ubl.common.PrepaidAmountType;
import org.openfact.models.ubl.common.TaxExclusiveAmountType;
import org.openfact.models.ubl.common.TaxInclusiveAmountType;

public class MonetaryTotalType {

    protected LineExtensionAmountType lineExtensionAmount;
    protected TaxExclusiveAmountType taxExclusiveAmount;
    protected TaxInclusiveAmountType taxInclusiveAmount;
    protected AllowanceTotalAmountType allowanceTotalAmount;
    protected ChargeTotalAmountType chargeTotalAmount;
    protected PrepaidAmountType prepaidAmount;
    protected PayableRoundingAmountType payableRoundingAmount;
    protected PayableAmountType payableAmount;
    protected String id;

    public LineExtensionAmountType getLineExtensionAmount() {
        return lineExtensionAmount;
    }

    public void setLineExtensionAmount(LineExtensionAmountType value) {
        this.lineExtensionAmount = value;
    }

    public TaxExclusiveAmountType getTaxExclusiveAmount() {
        return taxExclusiveAmount;
    }

    public void setTaxExclusiveAmount(TaxExclusiveAmountType value) {
        this.taxExclusiveAmount = value;
    }

    public TaxInclusiveAmountType getTaxInclusiveAmount() {
        return taxInclusiveAmount;
    }

    public void setTaxInclusiveAmount(TaxInclusiveAmountType value) {
        this.taxInclusiveAmount = value;
    }

    public AllowanceTotalAmountType getAllowanceTotalAmount() {
        return allowanceTotalAmount;
    }

    public void setAllowanceTotalAmount(AllowanceTotalAmountType value) {
        this.allowanceTotalAmount = value;
    }

    public ChargeTotalAmountType getChargeTotalAmount() {
        return chargeTotalAmount;
    }

    public void setChargeTotalAmount(ChargeTotalAmountType value) {
        this.chargeTotalAmount = value;
    }

    public PrepaidAmountType getPrepaidAmount() {
        return prepaidAmount;
    }

    public void setPrepaidAmount(PrepaidAmountType value) {
        this.prepaidAmount = value;
    }

    public PayableRoundingAmountType getPayableRoundingAmount() {
        return payableRoundingAmount;
    }

    public void setPayableRoundingAmount(PayableRoundingAmountType value) {
        this.payableRoundingAmount = value;
    }

    public PayableAmountType getPayableAmount() {
        return payableAmount;
    }

    public void setPayableAmount(PayableAmountType value) {
        this.payableAmount = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
