//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import org.openfact.models.ubl.common.AdditionalAccountIDType;
import org.openfact.models.ubl.common.ContactType;
import org.openfact.models.ubl.common.CustomerAssignedAccountIDType;
import org.openfact.models.ubl.common.DataSendingCapabilityType;
import org.openfact.models.ubl.common.PartyType;

public class SupplierPartyType {

    protected CustomerAssignedAccountIDType customerAssignedAccountID;
    protected List<AdditionalAccountIDType> additionalAccountID;
    protected DataSendingCapabilityType dataSendingCapability;
    protected PartyType party;
    protected ContactType despatchContact;
    protected ContactType accountingContact;
    protected ContactType sellerContact;
    protected String id;

    public CustomerAssignedAccountIDType getCustomerAssignedAccountID() {
        return customerAssignedAccountID;
    }

    public void setCustomerAssignedAccountID(CustomerAssignedAccountIDType value) {
        this.customerAssignedAccountID = value;
    }

    public List<AdditionalAccountIDType> getAdditionalAccountID() {
        if (additionalAccountID == null) {
            additionalAccountID = new ArrayList<AdditionalAccountIDType>();
        }
        return this.additionalAccountID;
    }

    public void setAdditionalAccountID(List<AdditionalAccountIDType> additionalAccountID) {
        this.additionalAccountID = additionalAccountID;
    }

    public DataSendingCapabilityType getDataSendingCapability() {
        return dataSendingCapability;
    }

    public void setDataSendingCapability(DataSendingCapabilityType value) {
        this.dataSendingCapability = value;
    }

    public PartyType getParty() {
        return party;
    }

    public void setParty(PartyType value) {
        this.party = value;
    }

    public ContactType getDespatchContact() {
        return despatchContact;
    }

    public void setDespatchContact(ContactType value) {
        this.despatchContact = value;
    }

    public ContactType getAccountingContact() {
        return accountingContact;
    }

    public void setAccountingContact(ContactType value) {
        this.accountingContact = value;
    }

    public ContactType getSellerContact() {
        return sellerContact;
    }

    public void setSellerContact(ContactType value) {
        this.sellerContact = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
