//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name = "BILLINGREFERENCE")
public class BillingReferenceEntity {

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    protected String id;

    @ManyToOne(targetEntity = DocumentReferenceEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "INVOICEDOCUMENTREFERENCE_BIL")
    protected DocumentReferenceEntity invoiceDocumentReference;

    @ManyToOne(targetEntity = DocumentReferenceEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "SELFBILLEDINVOICEDOCUMENTREF")
    protected DocumentReferenceEntity selfBilledInvoiceDocumentReference;

    @ManyToOne(targetEntity = DocumentReferenceEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "CREDITNOTEDOCUMENTREFERENCE")
    protected DocumentReferenceEntity creditNoteDocumentReference;

    @ManyToOne(targetEntity = DocumentReferenceEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "SELFBILLEDCREDITNOTEDOCUMENT")
    protected DocumentReferenceEntity selfBilledCreditNoteDocumentReference;

    @ManyToOne(targetEntity = DocumentReferenceEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "DEBITNOTEDOCUMENTREFERENCE")
    protected DocumentReferenceEntity debitNoteDocumentReference;

    @ManyToOne(targetEntity = DocumentReferenceEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "ADDITIONALDOCUMENTREFERENCE")
    protected DocumentReferenceEntity reminderDocumentReference;

    @OneToMany(targetEntity = BillingReferenceLineEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "BILLINGREFERENCELINE_BILLING")
    protected DocumentReferenceEntity additionalDocumentReference;

    @OneToMany(targetEntity = BillingReferenceLineEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "BILLINGREFERENCELINE_BILLING")
    protected List<BillingReferenceLineEntity> billingReferenceLine;

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     *            the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the invoiceDocumentReference
     */
    public DocumentReferenceEntity getInvoiceDocumentReference() {
        if (this.invoiceDocumentReference == null) {
            this.invoiceDocumentReference = new DocumentReferenceEntity();
        }
        return invoiceDocumentReference;
    }

    /**
     * @param invoiceDocumentReference
     *            the invoiceDocumentReference to set
     */
    public void setInvoiceDocumentReference(DocumentReferenceEntity invoiceDocumentReference) {
        this.invoiceDocumentReference = invoiceDocumentReference;
    }

    /**
     * @return the selfBilledInvoiceDocumentReference
     */
    public DocumentReferenceEntity getSelfBilledInvoiceDocumentReference() {
        if (this.selfBilledInvoiceDocumentReference == null) {
            this.selfBilledInvoiceDocumentReference = new DocumentReferenceEntity();
        }
        return selfBilledInvoiceDocumentReference;
    }

    /**
     * @param selfBilledInvoiceDocumentReference
     *            the selfBilledInvoiceDocumentReference to set
     */
    public void setSelfBilledInvoiceDocumentReference(
            DocumentReferenceEntity selfBilledInvoiceDocumentReference) {
        this.selfBilledInvoiceDocumentReference = selfBilledInvoiceDocumentReference;
    }

    /**
     * @return the creditNoteDocumentReference
     */
    public DocumentReferenceEntity getCreditNoteDocumentReference() {
        if (this.creditNoteDocumentReference == null) {
            this.creditNoteDocumentReference = new DocumentReferenceEntity();
        }
        return creditNoteDocumentReference;
    }

    /**
     * @param creditNoteDocumentReference
     *            the creditNoteDocumentReference to set
     */
    public void setCreditNoteDocumentReference(DocumentReferenceEntity creditNoteDocumentReference) {
        this.creditNoteDocumentReference = creditNoteDocumentReference;
    }

    /**
     * @return the selfBilledCreditNoteDocumentReference
     */
    public DocumentReferenceEntity getSelfBilledCreditNoteDocumentReference() {
        return selfBilledCreditNoteDocumentReference;
    }

    /**
     * @param selfBilledCreditNoteDocumentReference
     *            the selfBilledCreditNoteDocumentReference to set
     */
    public void setSelfBilledCreditNoteDocumentReference(
            DocumentReferenceEntity selfBilledCreditNoteDocumentReference) {
        if (this.selfBilledCreditNoteDocumentReference == null) {
            this.selfBilledCreditNoteDocumentReference = new DocumentReferenceEntity();
        }
        this.selfBilledCreditNoteDocumentReference = selfBilledCreditNoteDocumentReference;
    }

    /**
     * @return the debitNoteDocumentReference
     */
    public DocumentReferenceEntity getDebitNoteDocumentReference() {
        return debitNoteDocumentReference;
    }

    /**
     * @param debitNoteDocumentReference
     *            the debitNoteDocumentReference to set
     */
    public void setDebitNoteDocumentReference(DocumentReferenceEntity debitNoteDocumentReference) {
        if (this.debitNoteDocumentReference == null) {
            this.debitNoteDocumentReference = new DocumentReferenceEntity();
        }
        this.debitNoteDocumentReference = debitNoteDocumentReference;
    }

    /**
     * @return the reminderDocumentReference
     */
    public DocumentReferenceEntity getReminderDocumentReference() {
        return reminderDocumentReference;
    }

    /**
     * @param reminderDocumentReference
     *            the reminderDocumentReference to set
     */
    public void setReminderDocumentReference(DocumentReferenceEntity reminderDocumentReference) {
        if (this.reminderDocumentReference == null) {
            this.reminderDocumentReference = new DocumentReferenceEntity();
        }
        this.reminderDocumentReference = reminderDocumentReference;
    }

    /**
     * @return the additionalDocumentReference
     */
    public DocumentReferenceEntity getAdditionalDocumentReference() {
        return additionalDocumentReference;
    }

    /**
     * @param additionalDocumentReference
     *            the additionalDocumentReference to set
     */
    public void setAdditionalDocumentReference(DocumentReferenceEntity additionalDocumentReference) {
        if (this.additionalDocumentReference == null) {
            this.additionalDocumentReference = new DocumentReferenceEntity();
        }
        this.additionalDocumentReference = additionalDocumentReference;
    }

    /**
     * @return the billingReferenceLine
     */
    public List<BillingReferenceLineEntity> getBillingReferenceLine() {
        if (this.billingReferenceLine == null) {
            this.billingReferenceLine = new ArrayList<>();
        }
        return billingReferenceLine;
    }

    /**
     * @param billingReferenceLine
     *            the billingReferenceLine to set
     */
    public void setBillingReferenceLine(List<BillingReferenceLineEntity> billingReferenceLine) {
        this.billingReferenceLine = billingReferenceLine;
    }

}
