//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.openfact.models.ubl.common.IdentificationCodeType;
import org.openfact.models.ubl.common.NameTypeCommBas;

@Entity(name = "CountryType")
@Table(name = "COUNTRYTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class CountryType {

    protected IdentificationCodeType IDentificationCode;
    protected NameTypeCommBas name;
    protected String id;

    @ManyToOne(targetEntity = IdentificationCodeType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "IDENTIFICATIONCODE_COUNTRYTY_0")
    public IdentificationCodeType getIdentificationCode() {
        return IDentificationCode;
    }

    public void setIdentificationCode(IdentificationCodeType value) {
        this.IDentificationCode = value;
    }

    @ManyToOne(targetEntity = NameTypeCommBas.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "NAME__COUNTRYTYPE_OFID")
    public NameTypeCommBas getName() {
        return name;
    }

    public void setName(NameTypeCommBas value) {
        this.name = value;
    }

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
