/*******************************************************************************
 * Copyright 2016 Sistcoop, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name = "LOCATIONCOORDINATE")
public class LocationCoordinateEntity {

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    protected String id;

    @Column(name = "COORDINATE_SYSTEM_CODE")
    protected String coordinateSystemCode;

    @ManyToOne(targetEntity = MeasureEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "LATITUDEDEGREESMEASURE")
    protected MeasureEntity latitudeDegreesMeasure = new MeasureEntity();

    @ManyToOne(targetEntity = MeasureEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "LATITUDEMINUTESMEASURE")
    protected MeasureEntity latitudeMinutesMeasure = new MeasureEntity();

    @Column(name = "LATITUDE_DIRECTION_CODE")
    protected String latitudeDirectionCode;

    @ManyToOne(targetEntity = MeasureEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "LONGITUDEDEGREESMEASURE")
    protected MeasureEntity longitudeDegreesMeasure = new MeasureEntity();

    @ManyToOne(targetEntity = MeasureEntity.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "LONGITUDEMINUTESMEASURE")
    protected MeasureEntity longitudeMinutesMeasure = new MeasureEntity();

    @Column(name = "LONGITUDE_DIRECTION_CODE")
    protected String longitudeDirectionCode;

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     *            the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the coordinateSystemCode
     */
    public String getCoordinateSystemCode() {
        return coordinateSystemCode;
    }

    /**
     * @param coordinateSystemCode
     *            the coordinateSystemCode to set
     */
    public void setCoordinateSystemCode(String coordinateSystemCode) {
        this.coordinateSystemCode = coordinateSystemCode;
    }

    /**
     * @return the latitudeDegreesMeasure
     */
    public MeasureEntity getLatitudeDegreesMeasure() {
        return latitudeDegreesMeasure;
    }

    /**
     * @param latitudeDegreesMeasure
     *            the latitudeDegreesMeasure to set
     */
    public void setLatitudeDegreesMeasure(MeasureEntity latitudeDegreesMeasure) {
        this.latitudeDegreesMeasure = latitudeDegreesMeasure;
    }

    /**
     * @return the latitudeMinutesMeasure
     */
    public MeasureEntity getLatitudeMinutesMeasure() {
        return latitudeMinutesMeasure;
    }

    /**
     * @param latitudeMinutesMeasure
     *            the latitudeMinutesMeasure to set
     */
    public void setLatitudeMinutesMeasure(MeasureEntity latitudeMinutesMeasure) {
        this.latitudeMinutesMeasure = latitudeMinutesMeasure;
    }

    /**
     * @return the latitudeDirectionCode
     */
    public String getLatitudeDirectionCode() {
        return latitudeDirectionCode;
    }

    /**
     * @param latitudeDirectionCode
     *            the latitudeDirectionCode to set
     */
    public void setLatitudeDirectionCode(String latitudeDirectionCode) {
        this.latitudeDirectionCode = latitudeDirectionCode;
    }

    /**
     * @return the longitudeDegreesMeasure
     */
    public MeasureEntity getLongitudeDegreesMeasure() {
        return longitudeDegreesMeasure;
    }

    /**
     * @param longitudeDegreesMeasure
     *            the longitudeDegreesMeasure to set
     */
    public void setLongitudeDegreesMeasure(MeasureEntity longitudeDegreesMeasure) {
        this.longitudeDegreesMeasure = longitudeDegreesMeasure;
    }

    /**
     * @return the longitudeMinutesMeasure
     */
    public MeasureEntity getLongitudeMinutesMeasure() {
        return longitudeMinutesMeasure;
    }

    /**
     * @param longitudeMinutesMeasure
     *            the longitudeMinutesMeasure to set
     */
    public void setLongitudeMinutesMeasure(MeasureEntity longitudeMinutesMeasure) {
        this.longitudeMinutesMeasure = longitudeMinutesMeasure;
    }

    /**
     * @return the longitudeDirectionCode
     */
    public String getLongitudeDirectionCode() {
        return longitudeDirectionCode;
    }

    /**
     * @param longitudeDirectionCode
     *            the longitudeDirectionCode to set
     */
    public void setLongitudeDirectionCode(String longitudeDirectionCode) {
        this.longitudeDirectionCode = longitudeDirectionCode;
    }

}
