/*******************************************************************************
 * Copyright 2016 Sistcoop, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name = "MONETARYTOTAL")
public class MonetaryTotalEntity {

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    protected String id;

    @Column(name = "LINE_EXTENSION_AMOUNT")
    protected BigDecimal lineExtensionAmount;

    @Column(name = "TAX_EXCLUSIVE_AMOUNT")
    protected BigDecimal taxExclusiveAmount;

    @Column(name = "TAX_INCLUSIVE_AMOUNT")
    protected BigDecimal taxInclusiveAmount;

    @Column(name = "ALLOWANCE_TOTAL_AMOUNT")
    protected BigDecimal allowanceTotalAmount;

    @Column(name = "CHARGE_TOTAL_AMOUNT")
    protected BigDecimal chargeTotalAmount;

    @Column(name = "PREPAID_AMOUNT")
    protected BigDecimal prepaidAmount;

    @Column(name = "PAYABLE_ROUNDING_AMOUNT")
    protected BigDecimal payableRoundingAmount;

    @Column(name = "PAYABLE_AMOUNT")
    protected BigDecimal payableAmount;

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     *            the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the lineExtensionAmount
     */
    public BigDecimal getLineExtensionAmount() {
        return lineExtensionAmount;
    }

    /**
     * @param lineExtensionAmount
     *            the lineExtensionAmount to set
     */
    public void setLineExtensionAmount(BigDecimal lineExtensionAmount) {
        this.lineExtensionAmount = lineExtensionAmount;
    }

    /**
     * @return the taxExclusiveAmount
     */
    public BigDecimal getTaxExclusiveAmount() {
        return taxExclusiveAmount;
    }

    /**
     * @param taxExclusiveAmount
     *            the taxExclusiveAmount to set
     */
    public void setTaxExclusiveAmount(BigDecimal taxExclusiveAmount) {
        this.taxExclusiveAmount = taxExclusiveAmount;
    }

    /**
     * @return the taxInclusiveAmount
     */
    public BigDecimal getTaxInclusiveAmount() {
        return taxInclusiveAmount;
    }

    /**
     * @param taxInclusiveAmount
     *            the taxInclusiveAmount to set
     */
    public void setTaxInclusiveAmount(BigDecimal taxInclusiveAmount) {
        this.taxInclusiveAmount = taxInclusiveAmount;
    }

    /**
     * @return the allowanceTotalAmount
     */
    public BigDecimal getAllowanceTotalAmount() {
        return allowanceTotalAmount;
    }

    /**
     * @param allowanceTotalAmount
     *            the allowanceTotalAmount to set
     */
    public void setAllowanceTotalAmount(BigDecimal allowanceTotalAmount) {
        this.allowanceTotalAmount = allowanceTotalAmount;
    }

    /**
     * @return the chargeTotalAmount
     */
    public BigDecimal getChargeTotalAmount() {
        return chargeTotalAmount;
    }

    /**
     * @param chargeTotalAmount
     *            the chargeTotalAmount to set
     */
    public void setChargeTotalAmount(BigDecimal chargeTotalAmount) {
        this.chargeTotalAmount = chargeTotalAmount;
    }

    /**
     * @return the prepaidAmount
     */
    public BigDecimal getPrepaidAmount() {
        return prepaidAmount;
    }

    /**
     * @param prepaidAmount
     *            the prepaidAmount to set
     */
    public void setPrepaidAmount(BigDecimal prepaidAmount) {
        this.prepaidAmount = prepaidAmount;
    }

    /**
     * @return the payableRoundingAmount
     */
    public BigDecimal getPayableRoundingAmount() {
        return payableRoundingAmount;
    }

    /**
     * @param payableRoundingAmount
     *            the payableRoundingAmount to set
     */
    public void setPayableRoundingAmount(BigDecimal payableRoundingAmount) {
        this.payableRoundingAmount = payableRoundingAmount;
    }

    /**
     * @return the payableAmount
     */
    public BigDecimal getPayableAmount() {
        return payableAmount;
    }

    /**
     * @param payableAmount
     *            the payableAmount to set
     */
    public void setPayableAmount(BigDecimal payableAmount) {
        this.payableAmount = payableAmount;
    }

}
