//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity(name = "PaymentTermsType")
@Table(name = "PAYMENTTERMSTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class PaymentTermsType {

    protected IDType ID;
    protected PaymentMeansIDType paymentMeansID;
    protected PrepaidPaymentReferenceIDType prepaidPaymentReferenceID;
    protected List<NoteType> note;
    protected ReferenceEventCodeType referenceEventCode;
    protected SettlementDiscountPercentType settlementDiscountPercent;
    protected PenaltySurchargePercentType penaltySurchargePercent;
    protected AmountTypeCommBas amount;
    protected PeriodType settlementPeriod;
    protected PeriodType penaltyPeriod;
    protected String id;

    @ManyToOne(targetEntity = IDType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "ID_PAYMENTTERMSTYPE_OFID")
    public IDType getID() {
        return ID;
    }

    public void setID(IDType value) {
        this.ID = value;
    }

    @ManyToOne(targetEntity = PaymentMeansIDType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "PAYMENTMEANSID_PAYMENTTERMST_0")
    public PaymentMeansIDType getPaymentMeansID() {
        return paymentMeansID;
    }

    public void setPaymentMeansID(PaymentMeansIDType value) {
        this.paymentMeansID = value;
    }

    @ManyToOne(targetEntity = PrepaidPaymentReferenceIDType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "PREPAIDPAYMENTREFERENCEID_PA_0")
    public PrepaidPaymentReferenceIDType getPrepaidPaymentReferenceID() {
        return prepaidPaymentReferenceID;
    }

    public void setPrepaidPaymentReferenceID(PrepaidPaymentReferenceIDType value) {
        this.prepaidPaymentReferenceID = value;
    }

    @OneToMany(targetEntity = NoteType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "NOTE_PAYMENTTERMSTYPE_OFID")
    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }

    public void setNote(List<NoteType> note) {
        this.note = note;
    }

    @ManyToOne(targetEntity = ReferenceEventCodeType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "REFERENCEEVENTCODE_PAYMENTTE_0")
    public ReferenceEventCodeType getReferenceEventCode() {
        return referenceEventCode;
    }

    public void setReferenceEventCode(ReferenceEventCodeType value) {
        this.referenceEventCode = value;
    }

    @ManyToOne(targetEntity = SettlementDiscountPercentType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "SETTLEMENTDISCOUNTPERCENT_PA_0")
    public SettlementDiscountPercentType getSettlementDiscountPercent() {
        return settlementDiscountPercent;
    }

    public void setSettlementDiscountPercent(SettlementDiscountPercentType value) {
        this.settlementDiscountPercent = value;
    }

    @ManyToOne(targetEntity = PenaltySurchargePercentType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "PENALTYSURCHARGEPERCENT_PAYM_0")
    public PenaltySurchargePercentType getPenaltySurchargePercent() {
        return penaltySurchargePercent;
    }

    public void setPenaltySurchargePercent(PenaltySurchargePercentType value) {
        this.penaltySurchargePercent = value;
    }

    @ManyToOne(targetEntity = AmountTypeCommBas.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "AMOUNT_PAYMENTTERMSTYPE_OFID")
    public AmountTypeCommBas getAmount() {
        return amount;
    }

    public void setAmount(AmountTypeCommBas value) {
        this.amount = value;
    }

    @ManyToOne(targetEntity = PeriodType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "SETTLEMENTPERIOD_PAYMENTTERM_0")
    public PeriodType getSettlementPeriod() {
        return settlementPeriod;
    }

    public void setSettlementPeriod(PeriodType value) {
        this.settlementPeriod = value;
    }

    @ManyToOne(targetEntity = PeriodType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "PENALTYPERIOD_PAYMENTTERMSTY_0")
    public PeriodType getPenaltyPeriod() {
        return penaltyPeriod;
    }

    public void setPenaltyPeriod(PeriodType value) {
        this.penaltyPeriod = value;
    }

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
