//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.openfact.models.ubl.common.ItemLocationQuantityType;
import org.openfact.models.ubl.common.PriceType;

@Entity(name = "PricingReferenceType")
@Table(name = "PRICINGREFERENCETYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class PricingReferenceType {

    protected ItemLocationQuantityType originalItemLocationQuantity;
    protected List<PriceType> alternativeConditionPrice;
    protected String id;

    @ManyToOne(targetEntity = ItemLocationQuantityType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "ORIGINALITEMLOCATIONQUANTITY_0")
    public ItemLocationQuantityType getOriginalItemLocationQuantity() {
        return originalItemLocationQuantity;
    }

    public void setOriginalItemLocationQuantity(ItemLocationQuantityType value) {
        this.originalItemLocationQuantity = value;
    }

    @OneToMany(targetEntity = PriceType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "ALTERNATIVECONDITIONPRICE_PR_0")
    public List<PriceType> getAlternativeConditionPrice() {
        if (alternativeConditionPrice == null) {
            alternativeConditionPrice = new ArrayList<PriceType>();
        }
        return this.alternativeConditionPrice;
    }

    public void setAlternativeConditionPrice(List<PriceType> alternativeConditionPrice) {
        this.alternativeConditionPrice = alternativeConditionPrice;
    }

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
