//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity(name = "ResponseType")
@Table(name = "RESPONSETYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class ResponseType {

    protected ReferenceIDType referenceID;
    protected ResponseCodeType responseCode;
    protected List<DescriptionType> description;
    protected String id;

    @ManyToOne(targetEntity = ReferenceIDType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "REFERENCEID_RESPONSETYPE_OFID")
    public ReferenceIDType getReferenceID() {
        return referenceID;
    }

    public void setReferenceID(ReferenceIDType value) {
        this.referenceID = value;
    }

    @ManyToOne(targetEntity = ResponseCodeType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "RESPONSECODE_RESPONSETYPE_HJ_0")
    public ResponseCodeType getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(ResponseCodeType value) {
        this.responseCode = value;
    }

    @OneToMany(targetEntity = DescriptionType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "DESCRIPTION_RESPONSETYPE_OFID")
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    public void setDescription(List<DescriptionType> description) {
        this.description = description;
    }

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
