//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 11:44:49 AM PET 
//

package org.openfact.models.jpa.entities.ubl.common;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity(name = "TaxCategoryType")
@Table(name = "TAXCATEGORYTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class TaxCategoryType {

    protected IDType ID;
    protected NameTypeCommBas name;
    protected PercentType percent;
    protected BaseUnitMeasureType baseUnitMeasure;
    protected PerUnitAmountType perUnitAmount;
    protected TaxExemptionReasonCodeType taxExemptionReasonCode;
    protected TaxExemptionReasonType taxExemptionReason;
    protected TierRangeType tierRange;
    protected TierRatePercentType tierRatePercent;
    protected TaxSchemeType taxScheme;
    protected String id;

    @ManyToOne(targetEntity = IDType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "ID_TAXCATEGORYTYPE_OFID")
    public IDType getID() {
        return ID;
    }

    public void setID(IDType value) {
        this.ID = value;
    }

    @ManyToOne(targetEntity = NameTypeCommBas.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "NAME__TAXCATEGORYTYPE_OFID")
    public NameTypeCommBas getName() {
        return name;
    }

    public void setName(NameTypeCommBas value) {
        this.name = value;
    }

    @ManyToOne(targetEntity = PercentType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "PERCENT_TAXCATEGORYTYPE_OFID")
    public PercentType getPercent() {
        return percent;
    }

    public void setPercent(PercentType value) {
        this.percent = value;
    }

    @ManyToOne(targetEntity = BaseUnitMeasureType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "BASEUNITMEASURE_TAXCATEGORYT_0")
    public BaseUnitMeasureType getBaseUnitMeasure() {
        return baseUnitMeasure;
    }

    public void setBaseUnitMeasure(BaseUnitMeasureType value) {
        this.baseUnitMeasure = value;
    }

    @ManyToOne(targetEntity = PerUnitAmountType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "PERUNITAMOUNT_TAXCATEGORYTYP_0")
    public PerUnitAmountType getPerUnitAmount() {
        return perUnitAmount;
    }

    public void setPerUnitAmount(PerUnitAmountType value) {
        this.perUnitAmount = value;
    }

    @ManyToOne(targetEntity = TaxExemptionReasonCodeType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "TAXEXEMPTIONREASONCODE_TAXCA_0")
    public TaxExemptionReasonCodeType getTaxExemptionReasonCode() {
        return taxExemptionReasonCode;
    }

    public void setTaxExemptionReasonCode(TaxExemptionReasonCodeType value) {
        this.taxExemptionReasonCode = value;
    }

    @ManyToOne(targetEntity = TaxExemptionReasonType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "TAXEXEMPTIONREASON_TAXCATEGO_0")
    public TaxExemptionReasonType getTaxExemptionReason() {
        return taxExemptionReason;
    }

    public void setTaxExemptionReason(TaxExemptionReasonType value) {
        this.taxExemptionReason = value;
    }

    @ManyToOne(targetEntity = TierRangeType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "TIERRANGE_TAXCATEGORYTYPE_HJ_0")
    public TierRangeType getTierRange() {
        return tierRange;
    }

    public void setTierRange(TierRangeType value) {
        this.tierRange = value;
    }

    @ManyToOne(targetEntity = TierRatePercentType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "TIERRATEPERCENT_TAXCATEGORYT_0")
    public TierRatePercentType getTierRatePercent() {
        return tierRatePercent;
    }

    public void setTierRatePercent(TierRatePercentType value) {
        this.tierRatePercent = value;
    }

    @ManyToOne(targetEntity = TaxSchemeType.class, cascade = { CascadeType.ALL })
    @JoinColumn(name = "TAXSCHEME_TAXCATEGORYTYPE_HJ_0")
    public TaxSchemeType getTaxScheme() {
        return taxScheme;
    }

    public void setTaxScheme(TaxSchemeType value) {
        this.taxScheme = value;
    }

    @Id
    @Column(name = "ID")
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Access(AccessType.PROPERTY)
    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
